export const inspireMePrompts = [
  "provolone cheese, bacon, bread, ginger",
  "sugar, crunchy jif peanut butter, cornflakes",
  "sweet butter, confectioners sugar, flaked coconut, condensed milk, nuts, vanilla, dipping chocolate",
  "macaroni, butter, salt, bacon, milk, flour, pepper, cream corn",
  "hamburger, sausage, onion, regular, american cheese, colby cheese",
  "chicken breasts, onion, garlic, great northern beans, black beans, green chilies, broccoli, garlic oil, butter, cajun seasoning, salt, oregano, thyme, black pepper, basil, worcestershire sauce, chicken broth, sour cream, chardonnay wine",
  "serrano peppers, garlic, celery, oregano, canola oil, vinegar, water, kosher salt, salt, black pepper",
  "sushi rice, nori seaweed, raw salmon, cucumber, avocado",
  "pasta, tomatoes, garlic, basil, olive oil, parmesan cheese",
  "rice noodles, bean sprouts, tofu, peanuts, lime, fish sauce",
  "tortillas, black beans, avocado, cilantro, lime, salsa",
  "naan bread, chickpeas, tomatoes, onions, yogurt, spices",
  "kimchi, tofu, gochujang paste, sesame oil, green onions",
  "tortilla chips, refried beans, jalapenos, cheddar cheese, salsa",
  "pho noodles, beef, star anise, cinnamon, ginger, basil, lime",
  "soba noodles, soy sauce, mirin, green onions, sesame seeds",
  "miso paste, tofu, seaweed, green onions, dashi broth",
  "plantains, black beans, rice, peppers, onions, cilantro",
  "empanada dough, ground beef, onions, bell peppers, olives, raisins",
  "couscous, chickpeas, tomatoes, cucumbers, parsley, lemon",
  "dashi broth, bonito flakes, soy sauce, mirin, seaweed",
  "pita bread, falafel, hummus, tahini, tomatoes, cucumbers",
  "pad thai noodles, shrimp, tofu, eggs, peanuts, tamarind paste",
  "phyllo dough, spinach, feta cheese, onions, dill",
  "rice paper wrappers, shrimp, vermicelli noodles, lettuce, mint, peanut sauce",
  "masa harina, pork, chili peppers, onions, garlic, achiote paste",
  "ramen noodles, pork belly, eggs, bamboo shoots, nori, green onions",
  "arepas, shredded beef, black beans, plantains, avocado",
  "jollof rice, chicken, tomatoes, onions, peppers, spices",
  "okonomiyaki flour mix, cabbage, bacon, eggs, mayonnaise, bonito flakes",
  "borscht, beets, potatoes, cabbage, sour cream, dill",
  "tagine, lamb, apricots, almonds, couscous, cinnamon, cumin",
  "samosa pastry, potatoes, peas, carrots, curry powder",
  "sushi-grade tuna, sesame seeds, soy sauce, avocado, wasabi",
  "schnitzel, potatoes, cucumber salad, lemon wedges",
  "dumpling wrappers, ground pork, napa cabbage, ginger, soy sauce",
  "pho noodles, chicken, lemongrass, lime, cilantro, sriracha",
  "bao buns, pork belly, hoisin sauce, pickled vegetables",
  "perogies, potatoes, onions, bacon, sour cream",
  "saffron rice, chicken, almonds, raisins, onions, spices",
  "baba ganoush, pita bread, grilled eggplant, tahini, lemon",
  "pupusas, refried beans, cheese, curtido (pickled cabbage)",
  "gyoza wrappers, shrimp, cabbage, garlic, ginger, soy sauce",
  "bahn mi bread, grilled pork, pickled carrots, cilantro, jalapenos",
  "shakshuka, eggs, tomatoes, bell peppers, onions, cumin",
  "tikka masala sauce, chicken, basmati rice, naan bread",
  "bibimbap rice, beef, spinach, carrots, mushrooms, gochujang sauce",
  "ceviche, white fish, lime juice, onions, cilantro, peppers",
  "tamales, masa dough, pork, chili sauce, banana leaves",
  "mole sauce, chicken, tortillas, sesame seeds, chocolate",
  "bibimbap rice, tofu, bean sprouts, spinach, kimchi, sesame oil",
  "hummus, falafel, tabbouleh, pita bread, tahini sauce",
  "curry paste, coconut milk, chicken, bell peppers, bamboo shoots",
  "jerk seasoning, chicken, rice and peas, plantains, cabbage salad",
];
